#Should be solution level file

version: "3.9"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
        - POSTGRES_USER=course
        - POSTGRES_PASSWORD=passw0rd
        - POSTGRES_DB=movies
    ports:
      - "5432:5432"